### ISSUE TITLE
tun2socks更换为hev-socks5-tunnel后与ubound冲突

### ISSUE THREAD

**Issue by chinchunchang** [Opnwall/pfSense-Proxy-Suite#1]
tun2socks配置：

```
tunnel:
  name: tun3000
  mtu: 9000
  multi-queue: true
  ipv4: 198.18.0.1
socks5:
  port: 1080
  address: 10.0.0.1
  udp: 'udp'
  pipeline: true
misc:
  log-level: error
```

重启ubound之后错误日志：
/status_services.php: The command '/usr/local/sbin/unbound -c /var/unbound/unbound.conf' returned exit code '1', the output was '[1742778572] unbound[29699:0] error: can't bind socket: Can't assign requested address for 10.10.0.2 port 53 [1742778572] unbound[29699:0] fatal error: could not open ports'

停止tun2socks之后启动ubound正常
